[tool.cube]
output_dir = "./outputs"

# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html
[tool.black]
line-length = 120

# https://beta.ruff.rs/docs/settings/
[tool.ruff]
target-version = "py310"
line-length = 120
show-fixes = true
ignore-init-module-imports = true

# https://beta.ruff.rs/docs/rules/
extend-select = [
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
    "TCH",  # flake8-type-checking
    "I",    # isort
#    "D",    # pydocstyle
    "NPY",  # NumPy-specific rules
    "C90",  # mccabe
]

[tool.ruff.isort]
known-first-party = ["./*"]
