name: actions-template-sync

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
     - name: Generate token to read from source repo # see: https://github.com/tibdex/github-app-token
       id: generate_token
       uses: tibdex/github-app-token@v1
       with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

     - name: actions-template-sync
       uses: AndreasAugustin/actions-template-sync@v0.8.0
       with:
        github_token: ${{ steps.generate_token.outputs.token }}
        source_repo_path: Alive1024/Cube-DL-Project-Template
        upstream_branch: main
        pr_labels: template-sync