name: Publishing to PyPI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publishing_to_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: abatilo/actions-poetry@v2

      - name: Poetry Build and Publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build --no-interaction
